<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>mdml</AssemblyName>
    <RootNamespace>Mdml.Cli</RootNamespace>
    <AssemblyTitle>mdml</AssemblyTitle>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mdml.Core\Mdml.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

</Project>
